### ISSUE TITLE
Jest Testing

### ISSUE THREAD

**Issue by Clayto30** [Clayto30/campus-connect#3]
**User Stories**

* As a user, I want the components and features to render successfully on the page

* As a user, I want to see tests using Jest that test the expectations of the rendering etc

**Comment by vsjanarthani** [comment]
![jest error](https://user-images.githubusercontent.com/77141659/124225031-9cd6e280-dabb-11eb-9655-64cf91aa8444.png)
Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance via options.

**Comment by vsjanarthani** [comment]
Not doing tests. Removing jest
